### PR TITLE
Move all logic to redirect page model

### PR DESCRIPTION
**Pull request by bezin**
Hey there,

as discussed in Issue #1, I moved all the logic to the new redirect page model. I added an isExternal() method as you suggested as well. For me everything works fine. Feel free review and merge, if you are happy with it :)

Cheers

### CODE REVIEW

**Comment by bezin** [comment]
I was just wondering, if we should keep the redirect in the template. If we merge this PR like it is right now, you end up with an empty page, if you enter the url of the artifical redirect page directly... If we keep the template file and simply use the new url method, we should be fine.

```
// templates/redirect.php
<?php go($page->url()); ?>
```

**Comment by flokosiol** [comment]
Thanks for your work! I will have a look at it as soon as possible and keep your additional comment in mind.

**Comment by flokosiol** [comment]
I merged everything to the develop branch, [re-added the template file](https://github.com/flokosiol/kirby-redirect/commit/ac6c843bd4330a51b762e9088842eba740908928) as [mentioned](https://github.com/flokosiol/kirby-redirect/pull/2#issuecomment-255521559) and fixed [two small issues](https://github.com/flokosiol/kirby-redirect/commit/017c7268e15cec2e1da9cc5eae6ad0ac75305160).

Would be awesome, if you could test again. If everything's fine, I'll push it to the master.

**Comment by bezin** [comment]
Thanks for your work and your fixes. Good catches! 
Unfortunately I found another issue I was not aware of: I tested the Redirect-To-First-Child functionality and ran into an infinite loop :(

**Steps to reproduce:**
1. Create a new page 'Foo' of type redirect (uri: foo)
2. Do not enter anything in the fields -> triggers redirect to first visible child
3. Add a new subpage to 'Foo', named 'Bar' of any other page type (uri: foo/bar)
4. Browse to /foo

**What happens?**
The issue occurs in the regular page model (kirby\kirby.php:570). Kirby invokes our redirect page model url method here. Since we set up this page to redirect to the first visible subpage, we invoke this subpages' url method. Now the regular page model is used for the subpage (which is correct), but it invokes the parent url method again (see kirby/core/page.php:176), which ends in an infinite loop.

So far I did not come up with a solution, but I keep trying...

**Comment by bezin** [comment]
I did find a solution, please see pr #3

**Comment by flokosiol** [comment]
Damn, you're right. I didn't check the "first child" solution. Luckily you did!

Your PR looks good at first glance, but I will do some testing. Maybe we'll get it done this time :)

After this much work, maybe we should increase the version number to 1.0. What do you think?

**Comment by bezin** [comment]
> Your PR looks good at first glance, but I will do some testing. Maybe we'll get it done this time :)

Yes, please take your time :D

> After this much work, maybe we should increase the version number to 1.0. What do you think?

I agree 👍

**Pull request merged**
