### PR TITLE
reintroduce controller and only handle external redirects within the model

### PR DESCRIPTION
**Pull request by bezin**
Hey there,
as mentioned in my previous pull request #2, I found a recursion issue with redirects to the first child page. 
I found a solution for this issue but I am afraid it means, we have to reintroduce the controller ;)

Now only the external redirect url is handled in the redirect page model and everything else is done in the controller. This still achieves that the absolute external url is used in the menu, which was the issue with the original implementation I wanted to fix. I may have been a little to eager ;)

I am really sorry for the inconvienience. Hope this fixes everything.

### CODE REVIEW

**Comment by flokosiol** [comment]
We are almost there …

I created a spreadsheet with (hopefully) all (rational) possible combinations and checked all of them. I found only one little copy & paste error in the controller, which is now fixed in the `develop` branch.

I'll test it again in a few days and hopefully I won't find any new issues … 😉

**Comment by bezin** [comment]
Nice work! Only you increased the version number to 3.0 instead of 1.0 ;)
What did you think about my comment regarding the isExternal() method?

**Comment by flokosiol** [comment]
Never ending story … I fixed the version number – thanks.

> What did you think about my comment regarding the isExternal() method?

I must admit, that I don't remember what it was. Sorry. I checked all the issues but couldn't find any comment. 😞  Maybe I'm blinded by routine, meanwhile …

**Comment by bezin** [comment]
Nevermind, I commented directly on a line of code in one commit and figured it might get lost:

I am not sure about checking in RedirectPageModel->isExternal() if the redirect target exists or not, because it is actually out of this functions scope. With this function we want to check, whether the redirect is external or not. This is the case, if $this->redirect() is empty AND $this->external() is set. It does not really matter if this internal target page exists or not, because the fallback for this should not be an external redirect, should it?

That also applies to the controller though, because now, if you enter a page uid in the panel and have an external url set as well AND the page uid links to a non-existing page, Kirby will redirect to the external page. Wouldn't it be better to throw a #404?

**Comment by flokosiol** [comment]
Thanks for the explanation. 

> It does not really matter if this internal target page exists or not, because the fallback for this should not be an external redirect, should it?
> 
> Wouldn't it be better to throw a #404?

Originally, I tried to prevent any errors. Therefore I set up a redirect to `home` as the last fallback. Keeping this in mind, I still think, that an external link could be a fallback for a non-existing internal page. I guess setting an internal **and** external target at the same time won't be the normal use case, but could be used as indented fallback – so why not?

I would prefer to keep it this way.

**Comment by bezin** [comment]
I agree that this (internal and external field filled out) will not happen frequently ;) Alright, that is settled then :)

**Pull request merged**
